spring:
  profiles:
    active: dev
    include:
      - base-addi
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: tbvjqlqlqlr@gmail.com
    password: jp025879
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
logging:
  level:
    root: info
    com.ll.Week_Mission: debug
    org.hibernate.type.descriptor.sql: trace
custom:
  site:
    name: MUTSA
    baseUrl: "http://localhost:8080"

